"""Regenerate the README figures from the committed result JSONs.

Everything here reads `results/reported/*.json` and needs nothing but matplotlib,
so a fresh clone can reproduce the figures on CPU in a second:

    python scripts/make_readme_figures.py

Figures that need activations (projection histograms, ROC) come from the GPU
phases and are regenerated by their own `make` targets, not by this script.
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
REPORTED = ROOT / "results" / "reported"
OUT = ROOT / "figures" / "reported"

INK = "#1b1f24"
MUTED = "#6b7280"


def load(name: str) -> dict:
    with open(REPORTED / f"{name}.json") as fh:
        return json.load(fh)


def headroom_ladder(out_path: Path) -> None:
    """The threat-model ladder: what each attacker class can actually reach.

    The point of the figure is the ordering, not any single bar. A discrete
    input-space search is the weakest attacker, a continuous embedding-space
    suffix is stronger, and direct activation edits are unconstrained. The
    Vicuna control sits alongside as evidence that the low discrete number
    reflects the model rather than a weak GCG implementation.
    """
    gcg = load("attacks_gcg")
    cont = load("attacks_continuous")
    interp = load("interp")
    vicuna = load("attacks_gcg_vicuna_fullset")

    bars = [
        ("Discrete\n(GCG suffix)", gcg["gcg_asr"], "#4878D0"),
        ("Continuous\n(embedding suffix)", cont["continuous_asr"], "#B07AA1"),
        (
            "Activation\n(directional ablation)",
            1.0 - interp["ablation_refusal_rate"],
            "#E15759",
        ),
    ]

    fig, ax = plt.subplots(figsize=(7.2, 4.2))
    xs = range(len(bars))
    ax.bar(xs, [b[1] for b in bars], color=[b[2] for b in bars], width=0.62)

    for x, (_, val, _) in zip(xs, bars):
        ax.text(x, val + 0.025, f"{val:.0%}", ha="center", va="bottom", fontsize=12, color=INK)

    ax.set_xticks(list(xs))
    ax.set_xticklabels([b[0] for b in bars], fontsize=10)
    ax.set_ylim(0, 1.16)
    ax.set_yticks([0, 0.25, 0.5, 0.75, 1.0])
    ax.set_yticklabels(["0%", "25%", "50%", "75%", "100%"])
    ax.set_ylabel("Attack success rate", fontsize=11)
    ax.set_title(
        "Attack success rises with attacker access, not with effort",
        fontsize=12.5,
        color=INK,
        pad=12,
    )
    ax.spines[["top", "right"]].set_visible(False)
    ax.grid(axis="y", color="#e5e7eb", lw=0.8)
    ax.set_axisbelow(True)

    v_asr = vicuna["running_asr"]
    ax.annotate(
        f"Same GCG reaches {v_asr:.0%} on the\n"
        f"Vicuna-7B control ({vicuna['completed']} prompts):\n"
        f"the 50% is the model, not the attack",
        xy=(0, bars[0][1]),
        xytext=(0.035, 0.60),
        textcoords="axes fraction",
        fontsize=9,
        color=MUTED,
        arrowprops={"arrowstyle": "->", "color": MUTED, "lw": 0.9},
    )

    fig.tight_layout()
    fig.savefig(out_path, dpi=160)
    plt.close(fig)


def detector_transfer(out_path: Path) -> None:
    """The one fitted refusal direction, reused unchanged across covert tampers."""
    detect = load("detect")
    backdoor = load("backdoor")
    em = load("em_organism")
    obf = load("obfuscated")

    rows = [
        ("Refusal removal\n(the fine-tune it was built on)", detect["malicious"]["auroc"]),
        ("Benign fine-tune control\n(should flag less)", detect["benign_control"]["auroc"]),
        ("Triggered backdoor\n(sleeper, trigger absent)", backdoor["detector_clean"]["auroc"]),
        ("Emergent misalignment\n(insecure-code fine-tune)", em["detector_auroc"]),
        ("Adaptive obfuscation\n(attacker moves second)", obf["adaptive_detector_auroc"]),
    ]

    fig, ax = plt.subplots(figsize=(7.2, 4.0))
    ys = range(len(rows))
    colors = ["#4878D0", "#9ca3af", "#59A14F", "#76B7B2", "#E15759"]
    ax.barh(list(ys), [r[1] for r in rows], color=colors, height=0.58)

    for y, (_, val) in zip(ys, rows):
        ax.text(val - 0.015, y, f"{val:.3f}", ha="right", va="center", color="white", fontsize=11)

    ax.axvline(0.5, color=MUTED, ls="--", lw=1)
    ax.text(0.5, -0.58, " chance", color=MUTED, fontsize=9, va="center")

    ax.set_yticks(list(ys))
    ax.set_yticklabels([r[0] for r in rows], fontsize=9.5)
    ax.invert_yaxis()
    ax.set_xlim(0, 1.04)
    ax.set_xlabel("Detection AUROC", fontsize=11)
    ax.set_title(
        "The same generation-time probe, reused unchanged",
        fontsize=12.5,
        color=INK,
        pad=12,
    )
    ax.spines[["top", "right"]].set_visible(False)
    ax.grid(axis="x", color="#e5e7eb", lw=0.8)
    ax.set_axisbelow(True)

    fig.tight_layout()
    fig.savefig(out_path, dpi=160)
    plt.close(fig)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    headroom_ladder(OUT / "headroom_ladder.png")
    detector_transfer(OUT / "detector_transfer.png")
    print(f"wrote figures to {OUT}")


if __name__ == "__main__":
    main()
